# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.user:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\User" ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -   method:    "initDenormalizationContext"
                arguments:
                    - { groups: [ "user" ] }
    resource.group:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Group" ]
        tags:      [ { name: "api.resource" } ]
    resource.address:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Address" ]
        tags:      [ { name: "api.resource" } ]